version: "3.6"
services:
  rating:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ".:/app"
    ports:
      - 5001:5001
    environment:
      - FLASK_RUN_PORT=5001
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/ratelenditdb_dev
      - DATABASE_TEST_URL=postgresql+psycopg2://postgres:postgres@db:5432/ratelenditdb_test
    depends_on:
      - db
    networks:
      - lendit_gateway

  db:
    image: postgres:13.2-alpine
    ports:
      - 5107:5432
    volumes:
      - ./project/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - lendit_gateway

networks:
  lendit_gateway:
    external: true
    driver: "bridge"
