"""Initial migration

Revision ID: b253657b1788
Revises: 
Create Date: 2021-03-11 02:06:35.868270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b253657b1788"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rate")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate",
        sa.Column("rateid", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("stars", sa.REAL(), autoincrement=False, nullable=False),
        sa.Column("review", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("report", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("reviewed", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("reviewer", sa.TEXT(), autoincrement=False, nullable=False),
        sa.CheckConstraint(
            "reviewed ~* '^[\\w\\-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$'::text",
            name="valid_reviewed_email",
        ),
        sa.CheckConstraint(
            "reviewer ~* '^[\\w\\-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$'::text",
            name="valid_reviewer_email",
        ),
        sa.CheckConstraint(
            "(stars >= (0)::double precision) AND (stars <= (5)::double precision)",
            name="valid_stars",
        ),
        sa.CheckConstraint("reviewed <> reviewer", name="valid_lender_user"),
        sa.PrimaryKeyConstraint("rateid", name="rate_pk"),
    )
    # ### end Alembic commands ###
