"""v1.0

Revision ID: f88b9890ed2a
Revises: 
Create Date: 2021-04-10 15:43:21.467183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f88b9890ed2a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rate", "report", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "rate",
        "review",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.drop_column("rate", "requestid")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rate",
        sa.Column("requestid", postgresql.UUID(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "rate",
        "review",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("''::text"),
    )
    op.alter_column("rate", "report", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
